---
# defaults file for pod-charlesreid1

username: "{{ nonroot_user }}"

# where pod-charlesreid1 is installed
pod_install_dir: "/home/{{ username }}/pod-charlesreid1"

# admin email
admin_email: "{{ charlesreid1_admin_email }}"

# ----------------
# charlesreid1.com nginx 
# configuration variables
server_name_default: "{{ charlesreid1_server_name_default }}"

nginx_subdomains_ip: "{{ charlesreid1_nginx_subdomains_ip }}"

port_default: "{{ charlesreid1_port_default }}"
port_gitea: "{{ charlesreid1_port_gitea }}"

port_ssl_default: "{{ charlesreid1_port_ssl_default }}"
port_ssl_gitea: "{{ charlesreid1_port_ssl_gitea }}"

# end nginx configuration variables
# ----------------

# gitea domain
gitea_app_name: "git.{{ server_name_default }}"
gitea_domain: "git.{{ server_name_default }}"

# gitea secrets should be set
# using variable stored in vault
gitea_secret_key: "{{ charlesreid1_gitea_secret_key }}"
gitea_internal_token: "{{ charlesreid1_gitea_internal_token }}"

# default mysql password should be set
# using variable stored in vault
mysql_password: "{{ charlesreid1_mysql_password }}"

# mediawiki secret key should be set using vault var
mediawiki_secretkey: "{{ charlesreid1_mediawiki_secretkey }}"

