---
# defaults file for pod-webhooks

username: "{{ nonroot_user }}"

# where pod-webhooks is installed
webhooks_install_dir: "/home/{{ username }}/pod-webhooks"

captain_hook_secret: "{{ charlesreid1_captain_hook_secret }}"

# check for letsencrypt certificates to these domains
# (since this pod hosts their respective pages)
subdomains:
  - "pages.charlesreid1.com"
  - "hooks.charlesreid1.com"
  - "bots.charlesreid1.com"

# any other config details,
# secrets, tokens, pws, or 
# api keys should go here.

