---
# defaults file for pod-webhooks

username: "{{ nonroot_user }}"

# where pod-webhooks is installed
webhooks_install_dir: "/home/{{ username }}/pod-webhooks"

# shared secret 
# # (must be entered every time you create a webhook)
captain_hook_secret: "{{ charlesreid1_captain_hook_secret }}"

# any other config details,
# secrets, tokens, pws, or 
# api keys should go here.

