---
# main playbook for 
# all nodes


- name: Initial setup root
  hosts: "{{ machine_name }}"
  roles:
    - role: init-root
      tags: init-root
      become: yes


- name: Install packages with aptitude
  hosts: "{{ machine_name }}"
  roles:
    - role: install-stuff
      tags: install-stuff
      become: yes


- name: Initial setup non-root
  hosts: "{{ machine_name }}"
  roles:
    - role: init-nonroot
      tags: init-nonroot


- name: Install docker and docker-compose
  hosts: "{{ machine_name }}"
  roles:
    - role: docker
      become: yes


# This will change the SSH port and restart the SSH server
- name: Set up SSH keys
  hosts: "{{ machine_name }}"
  roles:
    - role: sshkeys
      tags: sshkeys
