---
# main playbook for 
# all nodes


- name: Initial setup root
  hosts: servers
  roles:
    - role: init-root
      tags: init-root
      become: yes


- name: Install packages with aptitude
  hosts: servers
  roles:
    - role: install-stuff
      tags: install-stuff
      become: yes


- name: Initial setup non-root
  hosts: servers
  roles:
    - role: init-nonroot
      tags: init-nonroot


- name: Install docker and docker-compose
  hosts: servers
  roles:
    - role: docker
      become: yes


- name: Set up SSH keys
  hosts: servers
  roles:
    - role: sshkeys
      tags: sshkeys


- name: Set up dotfiles
  hosts: servers
  roles:
    - role: dotfiles
      tags: dotfiles


- name: Set up vim
  hosts: servers
  roles:
    - role: vim
      tags: vim


- name: Install pyenv
  hosts: servers
  roles:
    - role: pyenv
      tags: pyenv
      become: yes


- name: Install goenv
  hosts: servers
  roles:
    - role: goenv
      tags: goenv
      become: yes



      #- name: Install AWS credentials and tools
      #  hosts: servers
      #  roles:
      #    - role: aws
      #      tags: aws
      #      aws_secret_access_key: "{{ charlesreid1_aws_secret_access_key }}"
      #      aws_access_key_id: "{{ charlesreid1_aws_access_key_id }}"


