---
# main playbook for charlesreid1 docker pod


- import_tasks: base.yml
  hosts: servers
  tags: base-setup


  #- name: Install AWS credentials
  #  hosts: servers
  #  become: yes
  #  roles:
  #    - role: aws
  #      tags: aws
  #      aws_secret_access_key: "{{ charlesreid1_aws_secret_access_key }}"
  #      aws_access_key_id: "{{ charlesreid1_aws_access_key_id }}"


- name: Install charlesreid1 docker pod
  hosts: servers
  become: yes
  roles:
    - role: pod-charlesreid1
      tags: pod-charlesreid1

