---
# deploy dockprom pod to dev stage

- name: Install dockprom docker pod
  hosts: "{{ machine_name }}"
  vars:
  - install_client_service: "true"
  - dockprom_bind_ip: "192.168.30.50"
  roles:
  - role: pod-dockprom
    become: yes
