site_name: charlesreid1-ansible
site_url: https://charlesreid1-docker.github.io/charlesreid1-ansible
repo_name: charlesreid1-ansible
repo_url: https://git.charlesreid1.com/ansible/charlesreid1-ansible
edit_uri: ""

copyright: 'Copyright &copy; 2019 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT license</a>'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'dns'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - 'Index': 'index.md'
  - 'Quickstart': 'quickstart.md'
  - 'Ansible on Vagrant': 'ansible_vagrant.md'
  - 'Ansible on DigitalOcean': 'ansible_do.md'
  - 'Ansible Playbooks': 'ansible_playbooks.md'
  - 'Ansible Vault': 'ansible_vault.md'
  - 'Ansible Cowsay': 'ansible_cowsay.md'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


strict: true
