---
# main playbook for charlesreid1 docker pod


- name: Install SSL certificates for charlesreid1 docker pod
  roles:
    - role: letsencrypt
      tags: letsencrypt
      domain_name: "charlesreid1.com"


- name: Install charlesreid1 docker pod
  hosts: servers
  become: yes
  roles:
    - role: pod-charlesreid1
      tags: pod-charlesreid1
      mysql_password: "{{ charlesreid1_mysql_password }}"
      gitea_secret_key: "{{ charlesreid1_gitea_secret_key }}"
      gitea_internal_token: "{{ charlesreid1_gitea_internal_token }}"

