---
# main playbook for charlesreid1 docker pod


- name: Install SSL certificates for charlesreid1 docker pod
  hosts: servers
  become: yes
  roles:
    - role: letsencrypt
      tags: letsencrypt
      site_email: "charles@charlesreid1.com"
      domains:
        - "charlesreid1.com"
        - "www.charlesreid1.com"
        - "git.charlesreid1.com"
#
#        - "charlesreid1.blue"
#        - "www.charlesreid1.blue"
#        - "git.charlesreid1.blue"
#
#        - "charlesreid1.red"
#        - "www.charlesreid1.red"
#        - "git.charlesreid1.red"


- name: Install charlesreid1 docker pod
  hosts: servers
  become: yes
  roles:
    - role: pod-charlesreid1
      tags: pod-charlesreid1
      top_domain: "charlesreid1.com"
      mysql_password: "{{ charlesreid1_mysql_password }}"
      gitea_secret_key: "{{ charlesreid1_gitea_secret_key }}"
      gitea_internal_token: "{{ charlesreid1_gitea_internal_token }}"

