---
# main playbook for charlesreid1 docker pod


- name: Install charlesreid1 docker pod
  hosts: servers
  become: yes
  roles:
    - role: pod-charlesreid1
      tags: pod-charlesreid1
      mysql_password: charlesreid1_mysql_password

