---
# main playbook for charlesreid1 docker pod



- name: Install SSL certificates for charlesreid1 docker pod
  hosts: servers
  become: yes
  roles:
    - role: letsencrypt
      tags: letsencrypt
      site_email: "charles@charlesreid1.com"
      domains:
        - "charlesreid1.red"
        - "www.charlesreid1.red"
        - "git.charlesreid1.red"
        - "pages.charlesreid1.red"
        - "bots.charlesreid1.red"
        - "hooks.charlesreid1.red"



- name: Install charlesreid1 docker pod
  hosts: servers
  become: yes
  roles:
    - role: pod-charlesreid1
      tags: pod-charlesreid1
      charlesreid1_server_name_default: "charlesreid1.red"

