---
# main playbook for webhooks docker pod


# SSL certs are all handled by the pod-charlesreid1 compute node

- name: Install webhooks docker pod (pages.* and hooks.* and bots.* subdomains)
  hosts: servers
  become: yes
  roles:
    - role: pod-webhooks
      tags: pod-webhooks
      captain_hook_secret: "{{ charlesreid1_captain_hook_secret }}"
      server_name_default: "charlesreid1.red"

