---
# Playbook for postfix server


- name: Install postfix
  hosts: dorky
  roles:
    - postfix
  vars:
    postfix_raw_options:
      - |
        append_dot_mydomain = yes
        myorigin = /etc/mailname
    postfix_hostname: "charlesreid1.party"
    postfix_mailname: "charlesreid1.party"
