---
# by default, ubuntu has python3 but not python
# we have to fix this with a provision.yml

# Note: also see https://stackoverflow.com/a/34402816/463213 
# gather_facts: no is important because python is required to gather facts
- name: "Provision worker nodes to make sure they have python and prepare them for Ansible"
  hosts: servers
  become: yes
  gather_facts: no
  remote_user: root
  pre_tasks:
    - name: "Update aptitude"
      raw: sudo apt-get -y update
    - name: "Install python2"
      raw: sudo apt-get -y install python
    - name: Add the non-root user
      user:
        name: "{{ nonroot_user }}"
        shell: /bin/bash
        state: present
        createhome: yes

