# ---
# tasks file for dotfiles
#
# clean up this mess.
# use the debian dotfiles repo
# and the bootstrap.sh script.

# Start by cloning our debian dotfiles repo.
# 
# The debian dotfiles repo contains all the
# master versions of all the dotfiles.

- name: Clone the debian dotfiles repo
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com:charlesreid1/debian-dotfiles.git
    dest: "/home/{{ username }}/dotfiles"
    recursive: yes


# Use the bootstrap.sh script in the 
# dotfiles repo to install all the
# dotfiles for our nonroot user.
# ~/scripts/ -> machinename_scripts/ too.

- name: Run bootstrap.sh to install all dotfiles
  become: yes
  become_user: "{{ username }}"
  command: "/home/{{ username }}/dotfiles/dotfiles/bootstrap.sh -f"

