---
# tasks file for init-root


##############
# Machine name

- name: Set machine name with hostname command
  become: yes
  command: "hostname {{ machine_name }}"


- name: Create new /etc/hostname
  become: yes
  command: "echo {{ machine_name }} > /etc/hostname"


- name: Set hostname entry to 127.0.0.1 in /etc/hosts
  become: yes
  lineinfile:
    path: "/etc/hosts"
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{ machine_name }}"
    create: yes


############
# Sudoers

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


####################################
# Add non-root user to wheel group

- name: Add the non-root user to the wheel group
  user:
    name: "{{ nonroot_user }}"
    groups: wheel
    append: yes
    state: present


############
# System

- name: Set timezone
  become: yes
  command: timedatectl set-timezone America/Vancouver


###################
# Make temp dir

- name: Make /temp dir
  become: yes
  file:
    path: /temp
    state: directory
    mode: 0777
