---
# Variables for all roles
# 
# Since most of the defaults are set to the
# values we want anyway, this file only sets
# values for variables that require data from
# the vault.

# AWS credentials:
charlesreid1_aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
charlesreid1_aws_access_key_id: "{{ vault_aws_access_key_id }}"

nonroot_user: "charles"
ssh_key_email: "charlesreid1@gmail.com"

# pod-charlesreid1 requires a mysql password
charlesreid1_mysql_password: "{{ vault_mysql_password }}"

charlesreid1_gitea_secret_key: "{{ vault_gitea_secret_key }}"
charlesreid1_gitea_internal_token: "{{ vault_gitea_internal_token }}"

