---
# Variables for all roles
# 
# This file contains variables that
# need to be set using the vault,
# and variables that are used across
# multiple roles.


########################
# multi-role variables

nonroot_user: "charles"

# unix username
username: "{{ nonroot_user }}"

# SSH key owner
ssh_key_email: "charlesreid1@gmail.com"

# admin email
charlesreid1_admin_email: "charles@charlesreid1.com"

# nginx variables
charlesreid1_port_default: "80"
charlesreid1_port_gitea: "80"
charlesreid1_port_ssl_default: "443"
charlesreid1_port_ssl_gitea: "443"

# pyenv variables
pyenv_root: "/home/{{ username }}/.pyenv"
pyenv_versions:
  - 3.7.9
#  - miniconda3-4.3.30
#  - 3.7.5
#  - 3.8.0
pyenv_global_version: 3.7.9
pyenv_python: "{{ pyenv_root }}/versions/{{ pyenv_global_version }}/bin/python"
pyenv_pip: "{{ pyenv_root }}/versions/{{ pyenv_global_version }}/bin/pip"



# ports
ssh_port: 5778


########################
# vault variables


####################
# dockprom
charlesreid1_dockprom_admin_user: "{{ vault_dockprom_admin_user }}"
charlesreid1_dockprom_admin_pass: "{{ vault_dockprom_admin_pass }}"


####################
# base vault vars

# unix system password
base_system_password: "{{ vault_system_password }}"


####################
# uptime vault vars

# uptime details
charlesreid1_uptime_user: "{{ username }}"
charlesreid1_uptime_gmail_email: "{{ vault_uptime_gmail_email }}"
charlesreid1_uptime_gmail_password: "{{ vault_uptime_gmail_password }}"
charlesreid1_uptime_recipient_name: "{{ vault_uptime_recipient_name }}"
charlesreid1_uptime_recipient_email: "{{ vault_uptime_recipient_email }}"
charlesreid1_uptime_slack_apikey: "{{ vault_uptime_slack_apikey }}"
charlesreid1_uptime_slack_channel: "{{ vault_uptime_slack_channel }}"


####################
# charlesreid1 vault vars

# AWS credentials:
charlesreid1_aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
charlesreid1_aws_access_key_id: "{{ vault_aws_access_key_id }}"


# Secrets and stuff

# pod-charlesreid1 requires a mysql password
charlesreid1_mysql_password: "{{ vault_mysql_password }}"

# gitea secret key for web sessions
charlesreid1_gitea_secret_key: "{{ vault_gitea_secret_key }}"
charlesreid1_gitea_internal_token: "{{ vault_gitea_internal_token }}"

# mediawiki secret key for web sessions
charlesreid1_mediawiki_secretkey: "{{ vault_mediawiki_secretkey }}"
