---
# Variables for all roles
# 
# This file contains variables that
# need to be set using the vault,
# and variables that are used across
# multiple roles.


########################
# multi-role variables

nonroot_user: "charles"

# unix username
username: "{{ nonroot_user }}"

# SSH key owner
ssh_key_email: "charlesreid1@gmail.com"

# admin email
charlesreid1_admin_email: "charles@charlesreid1.com"

# nginx variables

charlesreid1_port_default: "80"
charlesreid1_port_gitea: "80"

charlesreid1_port_ssl_default: "443"
charlesreid1_port_ssl_gitea: "443"



########################
# vault variables

# unix system password
base_system_password: "{{ vault_system_password }}"

# AWS credentials:
charlesreid1_aws_secret_access_key: "{{ vault_aws_secret_access_key }}"
charlesreid1_aws_access_key_id: "{{ vault_aws_access_key_id }}"


# Secrets and stuff

# pod-charlesreid1 requires a mysql password
charlesreid1_mysql_password: "{{ vault_mysql_password }}"

# gitea secret key for web sessions
charlesreid1_gitea_secret_key: "{{ vault_gitea_secret_key }}"
charlesreid1_gitea_internal_token: "{{ vault_gitea_internal_token }}"

# mediawiki secret key for web sessions
charlesreid1_mediawiki_secretkey: "{{ vault_mediawiki_secretkey }}"
