---
# ginsberg bot flock
# 
# Process:
# - clone repo
# - install api keys
# - install bot keys
# - install startup service
# - enable startup service
# - start startup service


# #####################################
# CLONE GINSBERG BOT FLOCK


- name: Check if ginsberg repo is already cloned
  stat:
    path: "{{ ginsberg_path }}"
  register: ginsberg_clone_check
  tags:
    - bots
    - ginsberg
    - git


- name: Clone ginsberg repo
  become: yes
  become_user: "{{ username }}"
  git:
    repo: "https://github.com/charlesreid1-bots/ginsberg-bot-flock.git"
    dest: "{{ ginsberg_path }}"
    recursive: yes
  when:
    - "not ginsberg_clone_check.stat.exists"
  tags:
    - bots
    - ginsberg
    - git


- name: Pull ginsberg
  become: yes
  become_user: "{{ username }}"
  command: "git pull"
  args:
    chdir: "{{ pod_install_path }}"
  when:
    - "ginsberg_clone_check.stat.exists"
  tags:
    - bots
    - ginsberg
    - git


# #####################################
# SET UP BOT KEYS


- name: "Install API keys"
  copy: 
    src: "apikey.json.enc"
    dest: "{{ ginsberg_path }}/bot/apikeys.json"
    decrypt: yes
  tags:
    - bots
    - ginsberg
    - keys

- name: "Install zipped ginsberg Twitter keys"
  copy:
    src: "ginsberg_keys.zip.enc"
    dest: "{{ ginsberg_path }}/bot/ginsberg_keys.zip"
    decrypt: yes
  tags:
    - bots
    - ginsberg
    - keys
    
- name: "Unzip ginsberg Twitter keys"
  command: "unzip {{ ginsberg_path }}/bot/ginsberg_keys.zip -d {{ ginsberg_path }}/bot"
  tags:
    - bots
    - ginsberg
    - keys


# #####################################
# INSTALL STARTUP SERVICES
# 
# Check if bot startup service is installed.
# If not, install it.

- name: Check if ginsberg startup service is installed
  stat:
    path: /etc/systemd/system/ginsberg.service
  register: ginsberg_bot_service_check
  tags:
    - bots
    - ginsberg
    - bot-services


- name: Fetch the ginsberg startup service jinja template
  fetch:
    src: "{{ ginsberg_path }}/service/ginsberg.service.j2"
    dest: "/tmp/ginsberg.service.j2"
    flat: yes
    fail_on_missing: yes
  tags:
    - bots
    - ginsberg
    - bot-services


- name: Install the ginsberg startup service file
  become: yes
  template:
    src: "/tmp/ginsberg.service.j2"
    dest: "/etc/systemd/system/ginsberg.service"
    mode: 0774
  when:
    - "not ginsberg_service_check.stat.exists"
  tags:
    - bots
    - ginsberg
    - bot-services


- name: Enable ginsberg startup service
  become: yes
  command: "systemctl enable ginsberg"
  when:
    - "ginsberg_service_check.stat.exists"
  tags:
    - bots
    - ginsberg
    - bot-services
