---
# tasks file for pod-charlesreid1
# 
# Tasks:
# ------
#
# clone pod contents
#
# /www setup
#   server_name_default top level domain clone
# docker and docker compose checks
# mediawiki prep
# gitea prep
#
# construct the pod (docker-compose build)
# install service
# (port mapping in Dockerfile)
# (letsencrypt cert check)
# enable service

# clone pod contents
- include: pod_clone.yml

# /www setup
- include: www_setup.yml

# docker and docker compose checks
- include: docker_checks.yml

# nginx
- include: nginx_prep.yml

# mediawiki
- include: mw_prep.yml

# gitea
- include: gitea_prep.yml

# construct pod
- include: pod_construct.yml

# install pod service
- include: pod_services.yml

# certs
- include: certs.yml

# mediawiki fixes
- include: mw_fixes.yml

# enable pod service
- include: pod_enable.yml
