---
###########################
# Set up charlesreid1.com docker pod
#
# git.charlesreid1.com/docker/pod-charlesreid1
# git.charlesreid1.com/docker/d-nginx-charlesreid1
#
# Tasks:
# ------
#
# clone pod contents
#
# /www setup
#   server-name_default top level domain clone
# docker and docker compose checks
# mediawiki prep
# gitea prep
#
# construct the pod (docker-compose build)
# install service
# (port mapping in Dockerfile)
# (letsencrypt cert check)
# enable service
#
###########################


# #####################################
# CLONE POD-CHARLESREID1


# Check if we already cloned it
- name: Check if pod-charlesreid1 repo is already cloned
  stat:
    path: "{{ pod_install_dir }}"
  register: pod_charlesreid1_clone_check


# Clone it
- name: Clone pod-charlesreid1
  become: yes
  become_user: "{{ username }}"
  git:
    repo: 'https://github.com/charlesreid1-docker/pod-charlesreid1.git'
    dest: "{{ pod_install_dir }}"
    recursive: yes
  when:
    - "not pod_charlesreid1_clone_check.stat.exists"


# #####################################
# BUILD DOCKER-COMPOSE FILE FROM TEMPLATE
# 
# Note: Don't use sed to replace the MySQL password placeholder.
# Use the fetch module to copy the template from the remote machine
# (i.e., the one in the git repo) to the local directory.
# Then use the template module to use the template.

- name: Fetch the docker-compose template from the remote machine
  run_once: true
  fetch:
    src: "{{ pod_install_dir }}/docker-compose.yml.j2"
    dest: "/tmp/pod-charlesreid1-docker-compose.yml.j2"
    flat: yes
    fail_on_missing: yes


- name: Install the docker-compose file
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/pod-charlesreid1-docker-compose.yml.j2"
    dest: "{{ pod_install_dir }}/docker-compose.yml"
    mode: 0640


# #####################################
# SET UP /WWW DIRECTORY
#
# /www/<domain>/
#                 charlesreid1.com-src/   <-- clone of charlesreid1.com repo, src branch
#                 git/            <-- .git dir for charlesreid1.com repo gh-pages branch
#                 git.data/       <-- .git dir for charlesreid1-data
#                 htdocs/         <-- clone of charlesreid1.com repo gh-pages branch
#                     data/       <-- clone of charlesreid1-data
#


# Run the script (included in the pod-webhooks repo)
# to do the initial clone of the gh-pages branch
# into /www. The script checks if it already exists
# so we don't have to.

- name: "Run initial clone commands to set up htdocs at /www/{{ server_name_default }}"
  command: "{{ pod_install_dir }}/scripts/git_clone_www.sh {{ server_name_default }}"



# #####################################
# DOCKER/DOCKER COMPOSE

# The docker role, in the base playbook,
# will install docker-compose, but we want
# to double check that the executable exists

- name: Check that docker compose executable is available
  stat:
    path: "/usr/local/bin/docker-compose"
  register: pod_register_docker_compose


# Also make sure the docker daemon is running

- name: Enable docker service
  become: yes
  service:
    name: docker
    enabled: yes
    state: restarted
  tags:
    - pod-charlesreid1-services




# #####################################
# NGIX PREP
#
# prepare the config files for the 
# charlesreid1.com nginx server:
# - copy templates from remote machine
# - clean conf.d directory
# - copy rendered templates to remote machine


- name: Fetch d-nginx-charlesreid1 configuration templates from remote machine
  run_once: true
  fetch:
    src: "{{ pod_install_dir }}/d-nginx-charlesreid1/conf.d_templates/{{ item }}"
    dest: "/tmp/{{ item }}"
    flat: yes
    fail_on_missing: yes
  with_items:
    - "http.DOMAIN.conf.j2"
    - "https.DOMAIN.conf.j2"
    - "https.DOMAIN.subdomains.conf.j2"
  tags:
    - pod-charlesreid1-mw

- name: Clean d-nginx-charlesreid1 conf.d directory
  become: yes
  become_user: "{{ username }}"
  command: "python {{ pod_install_dir }}/d-nginx-charlesreid1/scripts/clean_config.py"


#- name: Install the d-nginx-charlesreid1 configuration templates
#  become: yes
#  become_user: "{{ username }}"
#  template:
#    src: "/tmp/{{ item.src_name }}"
#    dest: "{{ pod_install_dir }}/{{ item.dest_name }}"
#  with_items:
#    - { "src_name": "http.DOMAIN.conf.j2", "dest_name": "http.{{ server_name_default }}.conf"}
#    - { "src_name": "https.DOMAIN.conf.j2", "dest_name": "https.{{ server_name_default }}.conf"}
#    - { "src_name": "https.DOMAIN.subdomains.conf.j2", "dest_name": "https.{{ server_name_default }}.subdomains.conf"}

- name: Install the d-nginx-charlesreid1 http configuration templates
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/http.DOMAIN.conf.j2"
    dest: "{{ pod_install_dir }}/http.{{ server_name_default }}.conf"

- name: Install the d-nginx-charlesreid1 https configuration templates
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/https.DOMAIN.conf.j2"
    dest: "{{ pod_install_dir }}/https.{{ server_name_default }}.conf"

- name: Install the d-nginx-charlesreid1 https subdomains configuration templates
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/https.DOMAIN.subdomains.conf.j2"
    dest: "{{ pod_install_dir }}/https.{{ server_name_default }}.subdomains.conf"


# #####################################
# MEDIAWIKI PREP
#
# We have to build the extensions dir for the MediaWiki container
# /pod-charlesreid1/d-mediawiki/charlesreid1-config/mediawiki/build_extensions_dir.sh 
#
# Then we have to use the LocalSettings.php and
# Apache config file templates to configure
# the mediawiki container to run correctly.

- name: Check if extensions dir already exists
  stat:
    path: "{{ pod_install_dir }}/d-mediawiki/charlesreid1-config/mediawiki/extensions"
  register: extensions_dir_exists
  tags:
    - pod-charlesreid1-mw


- name: Make mediawiki extensions dir build script executable
  become: yes
  become_user: "{{ username }}"
  file:
    path: "{{ pod_install_dir }}/d-mediawiki/charlesreid1-config/mediawiki/build_extensions_dir.sh"
    mode: "u+x"
  when:
    - "not extensions_dir_exists.stat.exists"
  tags:
    - pod-charlesreid1-mw


- name: Build the mediawiki extensions dir
  become: yes
  become_user: "{{ username }}"
  command: "{{ pod_install_dir }}/d-mediawiki/charlesreid1-config/mediawiki/build_extensions_dir.sh"
  args:
    chdir: "{{ pod_install_dir }}/d-mediawiki/charlesreid1-config/mediawiki"
  when:
    - "not extensions_dir_exists.stat.exists"
  tags:
    - pod-charlesreid1-mw


# Deal with MediaWiki configuration templates:
# - LocalSettings.php
# - Apache config file

- name: Fetch the LocalSettings.php jinja template
  run_once: true
  fetch:
    src: "{{ pod_install_dir }}/d-mediawiki/charlesreid1-config/mediawiki/LocalSettings.php.j2"
    dest: "/tmp/LocalSettings.php.j2"
    flat: yes
    fail_on_missing: yes
  tags:
    - pod-charlesreid1-mw


- name: Install the LocalSettings.php file
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/LocalSettings.php.j2"
    dest: "{{ pod_install_dir }}/d-mediawiki/charlesreid1-config/mediawiki/LocalSettings.php"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640
  tags:
    - pod-charlesreid1-mw


- name: Fetch the Apache config jinja template
  run_once: true
  fetch:
    src: "{{ pod_install_dir }}/d-mediawiki/charlesreid1-config/apache/charlesreid1.wiki.conf.j2"
    dest: "/tmp/charlesreid1.wiki.conf.j2"
    flat: yes
    fail_on_missing: yes
  tags:
    - pod-charlesreid1-mw


- name: Install the Apache config file
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/charlesreid1.wiki.conf.j2"
    dest: "{{ pod_install_dir }}/d-mediawiki/charlesreid1-config/apache/charlesreid1.wiki.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640
  tags:
    - pod-charlesreid1-mw



# #####################################
# GITEA PREP
#
# We have to create an app.ini file,
# use a jinja template in the pod-charlesreid1 
# repository

- name: Fetch the app.ini jinja template
  run_once: true
  fetch:
    src: "{{ pod_install_dir }}/d-gitea/app.ini.j2"
    dest: "/tmp/app.ini.j2"
    flat: yes
    fail_on_missing: yes
  tags:
    - pod-charlesreid1-gitea


- name: Make the custom conf dir for app.ini
  become: yes
  file:
    dest: "{{ pod_install_dir }}/d-gitea/custom/conf"
    mode: "u+x"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - pod-charlesreid1-gitea


- name: Install the app.ini file
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/app.ini.j2"
    dest: "{{ pod_install_dir }}/d-gitea/custom/conf/app.ini"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640
  tags:
    - pod-charlesreid1-gitea



# #####################################
# CONSTRUCT THE POD
#
# This task is very time-consuming.

- name: Build pod-charlesreid1 from scratch
  become: yes
  become_user: "{{ username }}"
  command: "/usr/local/bin/docker-compose build --no-cache"
  args:
    chdir: "{{ pod_install_dir }}"
  when:
    - "pod_register_docker_compose.stat.exists"



# #####################################
# INSTALL STARTUP SERVICE
# 
# Check if the charlesreid1 docker pod service
# is installed. If not, install it.

- name: Check if pod-charlesreid1 service is installed
  stat:
    path: /etc/systemd/system/pod-charlesreid1.service
  register: pod_charlesreid1_service_check
  tags:
    - pod-charlesreid1-services


- name: Install pod-charlesreid1 service
  become: yes
  template:
    src: pod-charlesreid1.service.j2
    dest: /etc/systemd/system/pod-charlesreid1.service
    mode: 0664
  when:
    - "not pod_charlesreid1_service_check.stat.exists"
  tags:
    - pod-charlesreid1-services


# Make sure we called the LetsEncrypt role to install
# certs (fake or real) for each of the domains/subdomains.

- name: Check if LetsEncrypt cert for default server name is present
  tags:
    - letsencrypt
  stat:
    path: "/etc/letsencrypt/live/{{ server_name_default }}"
  register: register_letsencrypt_livecert_default

- name: Check if LetsEncrypt cert for gitea server name is present
  tags:
    - letsencrypt
  stat:
    path: "/etc/letsencrypt/live/{{ server_name_gitea }}"
  register: register_letsencrypt_livecert_gitea

#- name: Check if LetsEncrypt cert for files server name is present
#  tags:
#    - letsencrypt
#  stat:
#    path: "/etc/letsencrypt/live/{{ server_name_files }}"
#  register: register_letsencrypt_livecert_files


# If certs are present, start/restart the
# pod-charlesreid1 service.

- name: Enable pod-charlesreid1 service
  become: yes
  service:
    name: pod-charlesreid1
    enabled: yes
    state: restarted
  when:
    - "pod_register_docker_compose.stat.executable"
    - "register_letsencrypt_livecert_default.stat.exists"
    - "register_letsencrypt_livecert_gitea.stat.exists"
  tags:
    - pod-charlesreid1-services


# See the pod-charlesreid1 documentation
# pages for what to do from here.
#
# Specifically, restore:
# - mediawiki database backups
# - mediawiki files backups
# - gitea dump zip file
# - gitea avatars zip file
# 
# Restore scripts are located in the
# pod-charlesreid1 repository:
# - database restore script: utils-mysql
# - mediawiki image restore script: utils-mw
# - gitea database and avatar: utils-gitea


