---
# #####################################
# NGIX CONFIG PREP
#
# prepare the config files for the 
# charlesreid1.com nginx server:
# - copy templates from remote machine
# - clean conf.d directory
# - copy rendered templates to remote machine


- name: Clean d-nginx-charlesreid1 conf.d directory
  become: yes
  become_user: "{{ username }}"
  command: "python {{ pod_install_dir }}/d-nginx-charlesreid1/scripts/clean_config.py"
  tags:
    - pod-charlesreid1
    - pod-charlesreid1-nginx


# Install the d-nginx-charlesreid1 configuration templates
#
# -------------
# HTTP

- name: Fetch d-nginx-charlesreid1 http configuration templates from remote machine
  fetch:
    src: "{{ pod_install_dir }}/d-nginx-charlesreid1/conf.d_templates/http.DOMAIN.conf.j2"
    dest: "/tmp/http.DOMAIN.conf.j2"
    flat: yes
    fail_on_missing: yes
  tags:
    - pod-charlesreid1
    - pod-charlesreid1-nginx


- name: Install the d-nginx-charlesreid1 http configuration templates
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/http.DOMAIN.conf.j2"
    dest: "{{ pod_install_dir }}/d-nginx-charlesreid1/conf.d/http.{{ server_name_default }}.conf"
    force: yes
  tags:
    - pod-charlesreid1
    - pod-charlesreid1-nginx


# -------------
# HTTPS

- name: Fetch d-nginx-charlesreid1 https configuration templates from remote machine
  fetch:
    src: "{{ pod_install_dir }}/d-nginx-charlesreid1/conf.d_templates/https.DOMAIN.conf.j2"
    dest: "/tmp/https.DOMAIN.conf.j2"
    flat: yes
    fail_on_missing: yes
  tags:
    - pod-charlesreid1
    - pod-charlesreid1-nginx


- name: Install the d-nginx-charlesreid1 https configuration templates
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/https.DOMAIN.conf.j2"
    dest: "{{ pod_install_dir }}/d-nginx-charlesreid1/conf.d/https.{{ server_name_default }}.conf"
    force: yes
  tags:
    - pod-charlesreid1
    - pod-charlesreid1-nginx


# -------------
# HTTPS subdomains


- name: Fetch d-nginx-charlesreid1 https subdomains configuration templates from remote machine
  fetch:
    src: "{{ pod_install_dir }}/d-nginx-charlesreid1/conf.d_templates/https.DOMAIN.subdomains.conf.j2"
    dest: "/tmp/https.DOMAIN.subdomains.conf.j2"
    flat: yes
    fail_on_missing: yes
  tags:
    - pod-charlesreid1
    - pod-charlesreid1-nginx


- name: Install the d-nginx-charlesreid1 https subdomains configuration templates
  become: yes
  become_user: "{{ username }}"
  template:
    src: "/tmp/https.DOMAIN.subdomains.conf.j2"
    dest: "{{ pod_install_dir }}/d-nginx-charlesreid1/conf.d/https.{{ server_name_default }}.subdomains.conf"
    force: yes
  tags:
    - pod-charlesreid1
    - pod-charlesreid1-nginx

