---
# defaults file for uptime

username: "{{ nonroot_user }"

# uptime details
uptime_user: "{{ dorylus_uptime_user }}"
uptime_path: "/home/{{ username }}/uptime"
uptime_gmail_email: "{{ dorylus_uptime_gmail_email }}"
uptime_gmail_password: "{{ dorylus_uptime_gmail_password }}"
uptime_recipient_name: "{{ dorylus_uptime_recipient_name }}"
uptime_recipient_email: "{{ dorylus_uptime_recipient_email }}"
uptime_slack_apikey: "{{ dorylus_uptime_slack_apikey }}"
uptime_slack_channel: "{{ dorylus_uptime_slack_channel }}"

