---
# Install AWS credentials


- name: Create AWS directory for root user
  become: yes
  file: path=/root/.aws state=directory mode=0755

- name: Install AWS credentials for root user
  become: yes
  template: src=templates/credentials.j2 dest=/root/.aws/credentials mode=0700

- name: Create AWS directory for regular user
  become: yes
  file: path=/home/{{ nonroot_user }}/.aws state=directory owner={{ nonroot_user }} mode=0755

- name: Install AWS credentials for regular user
  become: yes
  template: src=templates/credentials.j2 dest=/home/{{ nonroot_user }}/.aws/credentials owner={{ nonroot_user }} mode=0700

