---
# tasks file for aws


- name: "Import awscli.yml (tasks to install AWS CLI)"
  import_tasks: awscli.yml
  tags:
    - aws_tools


- name: "Import credentials.yml (tasks to install AWS credentials)"
  import_tasks: credentials.yml
  tags:
    - aws_creds

