---
# tasks file for aws
#
#
# NOTE: Do not install the AWS cli via apt,
# it is broken! (s3 functionality)
# 
# instead, verify that pyenv has been installed,
# and use it to pip install awscli



- name: Check if pyenv installed
  stat:
    path: "{{ pyenv_install_dir }}"
  register: pyenv_installed
  when: pyenv_installed.stat.isdir


- name: Pip install awscli
  command: pip install --update awscli


- name: Create AWS directory for root user
  become: yes
  file: path=/root/.aws state=directory


- name: Install AWS credentials for root user
  become: yes
  template: src=templates/credentials.j2 dest=/root/.aws/credentials


- name: Create AWS directory for regular user
  become: yes
  file: path=/home/{{ nonroot_user }}/.aws state=directory


- name: Install AWS credentials for root user
  become: yes
  template: src=templates/credentials.j2 dest=/home/{{ nonroot_user }}/.aws/credentials


