---
# tasks file for install-stuff

- name: Add git ppa
  become: yes
  apt_repository:
    validate_certs: no
    repo: 'ppa:git-core/ppa'
    state: present

- name: Update aptitude
  apt: update_cache=yes
  tags:
    - apt

- name: Install packages
  become: yes
  apt:
    pkg:
    - git
    - vim
    - screen
    - aptitude
    - build-essential
    - curl
    - wget
    - unzip
    - openssh-server
    - ncdu
    - fail2ban
    - iotop
    - ssl-cert
    state: present
    update_cache: yes
  tags:
    - apt

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
  tags:
    - apt

