---
# tasks file for install-stuff

- name: Install packages
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - git 
    - vim
    - screen
    - aptitude
    - build-essential
    - curl
    - wget
    - graphviz
    - awscli
    - openssh-server
    - ncdu
    - fail2ban
    - iotop

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

