---
# tasks file for install-stuff

- name: Install packages
  become: yes
  apt:
    pkg:
    - git 
    - vim
    - screen
    - aptitude
    - build-essential
    - curl
    - wget
    - graphviz
    - openssh-server
    - ncdu
    - fail2ban
    - iotop
    state: present
    update_cache: yes
  tags:
    - apt

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
  tags:
    - apt

