---
# packages required for goenv
# 
# (inferred from the packages required
# for pyenv...)

- name: Install requirements
  become: yes
  apt:
    pkg:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - wget
    - curl
    - llvm
    - git
    state: present
    update_cache: yes
  tags:
    - apt
