---
# tasks file for init-charles

- name: "Add the user {{ username }}"
  user:
    name: "{{ username }}"
    shell: /bin/bash
    groups: wheel
    append: yes
    state: present
    createhome: yes

