---
# tasks file for pyenv

# Install any system packages required by pyenv
- include: packages.yml

# Install pyenv itself
- include: pyenv.yml

# Install versions of python
- include: python.yml

# Install any pip packages we know we will need
- include: pip.yml

