---
# packages required for pyenv

- name: Install requirements
  apt:
    pkg: 
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - wget
    - curl
    - llvm
    - git
    state: present
    update_cache: yes
  become: true
  become_user: root
