---
# pip install things
# using pyenv

- name: Pip install things
  tags:
    - pip
  command: "{{ pyenv_root }}/versions/{{ pyenv_global_version}}/bin/pip install --upgrade {{ item }}"
  with_items:
    - Markdown
    - pelican
    - mkdocs

