---
# install versions of python
# using pyenv

- name: Install python versions
  tags:
    - versions
  command: "{{ pyenv_root }}/bin/pyenv install -s {{ item }}"
  args:
    creates: "{{ pyenv_root }}/versions/{{ item }}"
  with_items:
    - "{{ pyenv_versions }}"
    - "{{ pyenv_global_version }}"
    - "{{ pyenv_project_versions|json_query('[*].version') }}"

- name: Set global python version
  tags:
    - global
  lineinfile:
    path: "{{ pyenv_root }}/version"
    regexp: "^{{ pyenv_global_version }}"
    line: "{{ pyenv_global_version }}"
    create: yes
  when: pyenv_global_version is defined

