---
# Clone the uptime repo/script/package


# Check if we already cloned the repo
- name: Check if charlesreid1-bots/uptime repo is already cloned
  stat:
    path: "{{ uptime_path }}"
  register: uptime_clone_check
  tags:
    - uptime
    - uptime-clone


# Clone it
- name: Clone charlesreid1-bots/uptime
  become: yes
  become_user: "{{ username }}"
  git:
    repo: 'https://github.com/charlesreid1-bots/uptime'
    dest: "{{ uptime_path }}"
    recursive: yes
  when:
    - "not uptime_clone_check.stat.exists"
  tags:
    - uptime
    - uptime-clone


# Pull it
- name: Pull charlesreid1-bots/uptime
  become: yes
  become_user: "{{ username }}"
  command: "git pull"
  args:
    chdir: "{{ uptime_path }}"
  when:
    - "uptime_clone_check.stat.exists"
  tags:
    - uptime
    - uptime-clone
