---
# Set up a virtual environment to run uptime as a service

# Procedure:
# - install virtualenv package
# - create the virtual env dir
# - source the activate script
# - pip install requirements.txt

- name: Pip install virtualenv
  become: yes
  become_user: "{{ username }}"
  command: "/home/{{ username }}/.pyenv/shims/pip install virtualenv"
  tags:
    - uptime
    - uptime-virtualenv


- name: Create an uptime virtual environment
  become: yes
  become_user: "{{ username }}"
  command: "{{ pyenv_python }} -m virtualenv -p python3.6 {{ uptime_path }}/vp"
  tags:
    - uptime
    - uptime-virtualenv


- name: Pip install uptime requirements.txt into the uptime virtual environment
  become: yes
  become_user: "{{ username }}"
  command: "{{ uptime_path }}/vp/bin/pip install -r {{ uptime_path }}/requirements.txt"
  tags:
    - uptime
    - uptime-virtualenv
