---
# tasks file for vim

- name: Create ~/.vim directory
  directory:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/home/{{ username }}/.vim"
    - "/home/{{ username }}/.vim/swap"
    - "/home/{{ username }}/.vim/undo"
    - "/home/{{ username }}/.vim/backups"
    - "/home/{{ username }}/.vim/syntax"

- name: Set vim as the editor
  become: yes
  copy:
    src: editorenv.sh
    dest: /etc/profile.d/editorenv.sh
    mode: 0755

