---
# tasks file for vim


- name: Set vim as the system-wide editor
  become: yes
  copy:
    src: editorenv.sh
    dest: /etc/profile.d/editorenv.sh
    mode: 0755


- name: Create ~/.vim directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/home/{{ username }}/.vim"
    - "/home/{{ username }}/.vim/swap"
    - "/home/{{ username }}/.vim/undo"
    - "/home/{{ username }}/.vim/backups"
    - "/home/{{ username }}/.vim/syntax"


- name: Install vimrc
  copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - ".vimrc"


