---
# tasks file for vim


- name: Set vim as the system-wide editor
  become: yes
  copy:
    src: editorenv.sh
    dest: /etc/profile.d/editorenv.sh
    mode: 0755


#####################
# create .vim dir

- name: Check if a .vim directory already exists
  become: yes
  become_user: "{{ username }}"
  stat:
    path: "/home/{{ username }}/.vim"
  register: user_dotvim


- name: Create ~/.vim directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: "/home/{{ username }}/.vim"
    state: directory
    mode: 0755
  when:
    - "not user_dotvim.stat.exists"

#############################
# create .vim dir contents

- name: "Copy contents of .vim dir into ~{{ username }}/.vim"
  become: yes
  become_user: "{{ username }}"
  file:
    path: "/home/{{ username }}/.vim/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - swap
    - undo
    - backups
    - syntax



###########################
# install .vimrc 
# (and related dotfiles)

- name: Install .vimrc and related dotfiles
  become: yes
  become_user: "{{ username }}"
  copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/.{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - "vimrc"



