---
# tasks file for vim
# 
# no reason to split these tasks up any further with tags

#################################
# system environment variables


- name: Set vim as the system-wide editor
  become: yes
  copy:
    src: editorenv.sh
    dest: /etc/profile.d/editorenv.sh
    mode: 0755


#####################
# create .vim dir


- name: Check if a .vim directory already exists
  become: yes
  become_user: "{{ username }}"
  stat:
    path: "/home/{{ username }}/.vim"
  register: user_dotvim


- name: Create ~/.vim directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: "/home/{{ username }}/.vim"
    state: directory
    mode: 0755
  when:
    - "not user_dotvim.stat.exists"


#############################
# create .vim dir contents


- name: Create .vim directory contents
  become: yes
  become_user: "{{ username }}"
  file:
    path: "/home/{{ username }}/.vim/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - swap
    - undo
    - backups
    - syntax
    - colors


##############################
# install vim pathogen


- name: Create autoload and bundle directories in .vim directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: "/home/{{ username }}/.vim/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - autoload
    - bundle


- name: Download pathogen to .vim/autoload
  become: yes
  become_user: "{{ username }}"
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "/home/{{ username }}/.vim/autoload/pathogen.vim"
    mode: 0755


############################
# install solarized color scheme

- name: Download solarized color scheme to ~/.vim/colors
  become: yes
  become_user: "{{ username }}"
  get_url:
    url: "https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim"
    dest: "/home/{{ username }}/.vim/colors/solarized.vim"
    mode: 0755


