---
# tasks file for sshkeys


#####################
# root 

- name: Generate SSH keys for root user
  become: yes
  shell: ssh-keygen -t rsa -N '' -b 4096 -f /root/.ssh/id_rsa -q -C "{{ ssh_key_email }}"

- name: Set permissions on .ssh directory
  become: yes
  file:
  - path: /root/.ssh
    recurse: yes
    mode: "u+rwx,g-wx,o-rwx"

- name: Copy the authorized keys file into the root .ssh directory
  become: yes
  file:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: 0600


#####################
# nonroot user
#
- name: Generate SSH keys for nonroot user
  become: yes
  shell: "ssh-keygen -t rsa -N '' -b 4096 -f /home/{{ username }}/.ssh/id_rsa -q -C \"{{ ssh_key_email }}\""

- name: Set permissions on .ssh directory
  become: yes
  file:
  - path: /root/.ssh
    recurse: yes
    mode: "u+rwx,g-wx,o-rwx"

- name: Copy the authorized keys file into the nonroot user .ssh directory
  become: yes
  file:
    src: authorized_keys
    dest: "/home/{{ username }}/.ssh/authorized_keys"
    mode: 0600

